import { Inter, Merriweather } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const merri = Merriweather({
  variable: "--font-merri",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create HRMS App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${merri.variable} h-full antialiased scroll-smooth dark`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-[#020817] text-slate-100 antialiased">
        {/* Global theme background shared by all pages */}
        <div className="global-theme-bg" aria-hidden="true" />
        <div className="flex-1 flex flex-col">{children}</div>
      </body>
    </html>
  );
}

